CREATE TABLE CLIENT (CLIENT_ID BIGINT NOT NULL, CLIENT_NAME VARCHAR(255), LINE1 VARCHAR(255), LINE2 VARCHAR(255), LINE3 VARCHAR(255), LINE4 VARCHAR(255), POSTCODE VARCHAR(255), EMAIL VARCHAR(255), FIRSTNAME VARCHAR(255), SURNAME VARCHAR(255), TELEPHONE VARCHAR(255), PRIMARY KEY (CLIENT_ID))
CREATE TABLE PROJECT (PROJECT_ID BIGINT NOT NULL, ENDDATE DATE, PROJECT_NAME VARCHAR(255), STARTDATE DATE, CLIENT_ID BIGINT, PRIMARY KEY (PROJECT_ID))
CREATE TABLE EMPLOYEE (EMPLOYEE_ID BIGINT NOT NULL, DOB DATE, FIRST_NAME VARCHAR(255), RATE DECIMAL(38), ROLE VARCHAR(255), LAST_NAME VARCHAR(255), LINE1 VARCHAR(255), LINE2 VARCHAR(255), LINE3 VARCHAR(255), LINE4 VARCHAR(255), POSTCODE VARCHAR(255), PRIMARY KEY (EMPLOYEE_ID))
CREATE TABLE TIMESHEET (TIMESHEET_ID BIGINT NOT NULL, DESCRIPTION VARCHAR(255), ENTRY_DATE DATE, HOURS_WORKED FLOAT, EMPLOYEE_ID BIGINT, PROJECT_ID BIGINT, PRIMARY KEY (TIMESHEET_ID))
CREATE TABLE EMP_PROJ (PROJECT_ID BIGINT NOT NULL, EMPLOYEE_ID BIGINT NOT NULL, PRIMARY KEY (PROJECT_ID, EMPLOYEE_ID))
ALTER TABLE PROJECT ADD CONSTRAINT FK_PROJECT_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID)
ALTER TABLE TIMESHEET ADD CONSTRAINT FK_TIMESHEET_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID)
ALTER TABLE TIMESHEET ADD CONSTRAINT FK_TIMESHEET_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID)
ALTER TABLE EMP_PROJ ADD CONSTRAINT FK_EMP_PROJ_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID)
ALTER TABLE EMP_PROJ ADD CONSTRAINT FK_EMP_PROJ_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID)
CREATE SEQUENCE EMPLOYEE_ID_SEQ INCREMENT BY 50 START WITH 50
CREATE SEQUENCE PROJECT_ID_SEQ INCREMENT BY 50 START WITH 50
CREATE SEQUENCE CLIENT_ID_SEQ INCREMENT BY 50 START WITH 50
CREATE SEQUENCE TIMESHEET_ID_SEQ INCREMENT BY 50 START WITH 50
CREATE SEQUENCE TIMESHEET_ID_SEQ INCREMENT BY 50 START WITH 50
CREATE SEQUENCE EMPLOYEE_ID_SEQ INCREMENT BY 50 START WITH 50
CREATE SEQUENCE PROJECT_ID_SEQ INCREMENT BY 50 START WITH 50
CREATE SEQUENCE CLIENT_ID_SEQ INCREMENT BY 50 START WITH 50
