ALTER TABLE PROJECT DROP CONSTRAINT FK_PROJECT_CLIENT_ID
ALTER TABLE TIMESHEET DROP CONSTRAINT FK_TIMESHEET_PROJECT_ID
ALTER TABLE TIMESHEET DROP CONSTRAINT FK_TIMESHEET_EMPLOYEE_ID
ALTER TABLE EMP_PROJ DROP CONSTRAINT FK_EMP_PROJ_EMPLOYEE_ID
ALTER TABLE EMP_PROJ DROP CONSTRAINT FK_EMP_PROJ_PROJECT_ID
DROP TABLE CLIENT
DROP TABLE PROJECT
DROP TABLE EMPLOYEE
DROP TABLE TIMESHEET
DROP TABLE EMP_PROJ
DROP SEQUENCE EMPLOYEE_ID_SEQ
DROP SEQUENCE PROJECT_ID_SEQ
DROP SEQUENCE TIMESHEET_ID_SEQ
DROP SEQUENCE CLIENT_ID_SEQ
